'use strict'
module.exports = {
  NODE_ENV: '"production"',
  VUE_APP_CESIUM_TOKEN: '"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJmNzgwNjgyZS02NTZhLTQ1ZDktYjc0MS1jM2M2NDg4Y2YwNTgiLCJpZCI6MzEyNDM0LCJpYXQiOjE3NTAwMzQ2MTl9.iHI-mmi5PyXJJKrFVkYS7JrHWL1CPYufx24DvqS98Hc"'
}
